### ISSUE TITLE
Allow using existing Prometheus deployment

### ISSUE THREAD

**Issue by rg0now** [l7mp/stunner-helm#26]
The stunner-prometheus Helm chart deploys its own Prometheus, which makes it difficult to integrate with an existing deployment. This whislist item requests an Helm chart option to skip deploying a new Prometheus (and maybe also Grafana?).

**Comment by levaitamas** [comment]
I just tested that [`kube-prometheus-stack`](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) works with the following PodMonitor config:

> [!WARNING] 
> Set `enableMetricsEndpoint: true` in your Dataplane object first [[docs]](https://docs.l7mp.io/en/stable/MONITORING/)

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: stunner-podmonitor
  labels:
    metrics: stunner
    release: prometheus
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - honorLabels: True
    interval: 5s
    port: "metrics-port"
    path: "/metrics"
  selector:
    matchLabels:
      app: stunner
  namespaceSelector:
    matchNames:
      - stunner
      - stunner-system
      - default
```
