### ISSUE TITLE
Use standard gateway api bundle

### ISSUE THREAD

**Issue by davhdavh** [l7mp/stunner-helm#34]
The current gateway CRD is out of sync with current release, which is causing issues with other lib that also include gateway api.
Please use the standard bundle from upstream: `https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml`

**Comment by pandvan** [comment]
It would be great if the installation of CRDs are optional.
In the same cluster there could be another Gateway controller Helm chart that tries ti deploy upstream CRDs.

**Comment by davhdavh** [comment]
can we get this fixed? it is blocking from deploying anything else in cluster that has to do with gateway api

**Comment by levaitamas** [comment]
Hi!

> It would be great if the installation of CRDs are optional.

You can use the `--skip-crds` helm install flag to skip CRD installation. In this case,  you can use your gateway api version, but have to manually install the Stunner CRD in your cluster, as shown here:
```console
kubectl apply -f https://raw.githubusercontent.com/l7mp/stunner-helm/refs/heads/main/helm/stunner-gateway-operator/crds/stunner-crd.yaml
```

We are working on documenting this feature in the install guide.

**Comment by levaitamas** [comment]
> We are working on documenting this feature in the install guide.

Just for the record: https://docs.l7mp.io/en/latest/INSTALL/#skip-install-crds

**Comment by davhdavh** [comment]
I didnt think it was possible to set this per application in argocd, but seems they added the feature in 2.10...

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-services
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: ...
          revision: HEAD
          directories:
          - path: "cluster-services/*"
          pathParamPrefix: namespace
      - matrix:
          generators:
          - git:
              repoURL: ...
              revision: HEAD
              directories:
              - path: "{{`cluster-services/{{.namespace.path.basename}}/*`}}"
              pathParamPrefix: service
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  kubernetes.io/environment: dev
  template:
    metadata:
      name: '{{`cluster-services-{{.name}}-{{.service.path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: ...
        targetRevision: HEAD
        path: '{{`{{.service.path.path}}`}}'
        helm:
          ignoreMissingValueFiles: true
          releaseName: '{{`{{.service.path.basename}}`}}'
          valueFiles:
          - values.yaml
          - {{`values-{{.name}}.yaml`}}
      destination:
        name: '{{`{{.name}}`}}'
        namespace: '{{`{{.namespace.path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        retry:
          limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s
            factor: 3
            maxDuration: 3m
      ignoreDifferences:
      - group: storage.k8s.io
        kind: CSIDriver
        jsonPointers:
          - /spec/seLinuxMount
      - group: velero.io
        kind: Backup 
      - kind: PersistentVolume
        jsonPointers:
        - /spec/claimRef/resourceVersion
        - /spec/claimRef/uid
        - /status/lastPhaseTransitionTime
  templatePatch: |
    {{`{{- if eq .service.path.basename "stunner-gateway-operator" }}`}}
    spec:
      source:
        helm:
          skipCrds: true
    {{`{{- end }}`}}
```
